version: 2.1

parameters:
  canary:
    type: boolean
    default: false

jobs:
  test-go:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run:
          name: Set environment and execute commands
          environment:
            CANARY: << pipeline.parameters.canary >>
          command: |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace
            echo "export CANARY=${CANARY}"
            echo << pipeline.parameters.canary >>
      - run: sleep 15s

workflows:
  build-and-test:
    jobs:
      - test-go:
          filters:
            tags:
              only: /.*/
